-- Utsavaloka full platform schema
-- Fresh Supabase project recommended. Run once in SQL Editor.
create extension if not exists pgcrypto;
do $$ begin create type public.user_role as enum('super_admin','institution_admin','faculty','club_admin','student'); exception when duplicate_object then null; end $$;
do $$ begin create type public.record_status as enum('active','inactive','archived'); exception when duplicate_object then null; end $$;
do $$ begin create type public.event_status as enum('draft','published','registration_closed','live','completed','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.registration_status as enum('registered','waitlisted','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.certificate_status as enum('pending','issued','revoked'); exception when duplicate_object then null; end $$;

create table if not exists public.institutions(id uuid primary key default gen_random_uuid(),name text not null,code text unique,email text,phone text,website text,status public.record_status default 'active',created_at timestamptz default now());
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,institution_id uuid references public.institutions(id) on delete set null,display_name text,role public.user_role default 'student',status public.record_status default 'active',created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.departments(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,name text not null,code text not null,created_at timestamptz default now(),unique(institution_id,code));
create table if not exists public.students(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,profile_id uuid unique references public.profiles(id) on delete set null,department_id uuid references public.departments(id) on delete set null,student_number text not null,first_name text not null,last_name text not null,email text,phone text,year_of_study smallint,admission_year smallint,status public.record_status default 'active',created_at timestamptz default now(),unique(institution_id,student_number));
create table if not exists public.courses(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,department_id uuid references public.departments(id) on delete set null,code text not null,name text not null,credits numeric(4,1) default 0,created_at timestamptz default now(),unique(institution_id,code));
create table if not exists public.clubs(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,name text not null,slug text not null,description text,status public.record_status default 'active',created_at timestamptz default now(),unique(institution_id,slug));
create table if not exists public.club_members(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,club_id uuid not null references public.clubs(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,role text default 'member',joined_at timestamptz default now(),unique(club_id,student_id));
create table if not exists public.events(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,club_id uuid references public.clubs(id) on delete set null,created_by uuid references public.profiles(id) on delete set null,title text not null,description text,start_at timestamptz not null,end_at timestamptz,venue text,capacity integer default 0 check(capacity>=0),status public.event_status default 'draft',created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.event_registrations(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,event_id uuid not null references public.events(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,status public.registration_status default 'registered',registered_at timestamptz default now(),unique(event_id,student_id));
create table if not exists public.event_attendance_sessions(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,event_id uuid not null references public.events(id) on delete cascade,created_by uuid references public.profiles(id),token_hash text not null,expires_at timestamptz not null,created_at timestamptz default now(),unique(token_hash));
create table if not exists public.event_attendance(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,event_id uuid not null references public.events(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,session_id uuid references public.event_attendance_sessions(id) on delete set null,checked_in_at timestamptz default now(),method text default 'qr',unique(event_id,student_id));
create table if not exists public.participation_records(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,event_id uuid not null references public.events(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,role text default 'participant',created_at timestamptz default now(),unique(event_id,student_id));
create table if not exists public.certificates(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,event_id uuid references public.events(id) on delete set null,student_id uuid not null references public.students(id) on delete cascade,certificate_number text not null,title text not null,status public.certificate_status default 'pending',issued_at timestamptz,created_at timestamptz default now(),unique(institution_id,certificate_number));
create table if not exists public.notices(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,created_by uuid references public.profiles(id),title text not null,body text not null,published_at timestamptz,expires_at timestamptz,status public.record_status default 'active',created_at timestamptz default now());
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,profile_id uuid references public.profiles(id) on delete cascade,title text not null,body text not null,read_at timestamptz,created_at timestamptz default now());
create table if not exists public.circulars(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,created_by uuid references public.profiles(id),title text not null,body text not null,published_at timestamptz,expires_at timestamptz,status public.record_status default 'active',created_at timestamptz default now());
create table if not exists public.deadlines(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,created_by uuid references public.profiles(id),title text not null,description text,due_at timestamptz not null,status public.record_status default 'active',created_at timestamptz default now());
create table if not exists public.timetable_entries(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,course_id uuid not null references public.courses(id) on delete cascade,faculty_id uuid references public.profiles(id) on delete set null,day_of_week text not null,start_time time not null,end_time time not null,room text,created_at timestamptz default now());
create table if not exists public.exams(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,course_id uuid not null references public.courses(id) on delete cascade,name text not null,starts_at timestamptz not null,room text,max_marks numeric(7,2),status public.record_status default 'active',created_at timestamptz default now());
create table if not exists public.academic_attendance_sessions(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,course_id uuid not null references public.courses(id) on delete cascade,faculty_id uuid references public.profiles(id) on delete set null,starts_at timestamptz not null,created_at timestamptz default now());
create table if not exists public.academic_attendance(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,session_id uuid not null references public.academic_attendance_sessions(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,present boolean default false,marked_at timestamptz default now(),unique(session_id,student_id));
create table if not exists public.marks(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,course_id uuid not null references public.courses(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,assessment_name text not null,score numeric(7,2) not null,max_score numeric(7,2) not null,created_at timestamptz default now(),unique(course_id,student_id,assessment_name));
create table if not exists public.achievements(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,title text not null,category text,description text,achieved_on date,created_at timestamptz default now());
create table if not exists public.activity_records(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,activity_type text not null,reference_id uuid,description text,created_at timestamptz default now());
create table if not exists public.audit_logs(id uuid primary key default gen_random_uuid(),institution_id uuid references public.institutions(id) on delete cascade,actor_id uuid references public.profiles(id) on delete set null,action text not null,entity_type text not null,entity_id uuid,metadata jsonb default '{}'::jsonb,created_at timestamptz default now());

create index if not exists students_institution_idx on public.students(institution_id);
create index if not exists events_institution_start_idx on public.events(institution_id,start_at);
create index if not exists registrations_event_idx on public.event_registrations(event_id);
create index if not exists attendance_event_idx on public.event_attendance(event_id);
create index if not exists notifications_profile_idx on public.notifications(profile_id);
create index if not exists activity_student_idx on public.activity_records(student_id);

create schema if not exists private;
create or replace function private.current_institution_id() returns uuid language sql stable security definer set search_path='' as $$select institution_id from public.profiles where id=(select auth.uid())$$;
create or replace function private.current_role() returns public.user_role language sql stable security definer set search_path='' as $$select role from public.profiles where id=(select auth.uid())$$;
revoke all on function private.current_institution_id() from public;
revoke all on function private.current_role() from public;
grant usage on schema private to authenticated;
grant execute on function private.current_institution_id() to authenticated;
grant execute on function private.current_role() to authenticated;

do $$ declare t text; begin foreach t in array array['institutions','profiles','departments','students','courses','clubs','club_members','events','event_registrations','event_attendance_sessions','event_attendance','participation_records','certificates','notices','notifications','circulars','deadlines','timetable_entries','exams','academic_attendance_sessions','academic_attendance','marks','achievements','activity_records','audit_logs'] loop execute format('alter table public.%I enable row level security',t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); end loop; end $$;

create policy "institution members read institutions" on public.institutions for select to authenticated using(id=private.current_institution_id());
create policy "users read profiles" on public.profiles for select to authenticated using(id=(select auth.uid()) or institution_id=private.current_institution_id());
create policy "institution members manage departments" on public.departments for all to authenticated using(institution_id=private.current_institution_id() and private.current_role() in('super_admin','institution_admin')) with check(institution_id=private.current_institution_id());
create policy "institution members manage students" on public.students for all to authenticated using(institution_id=private.current_institution_id() and private.current_role() in('super_admin','institution_admin','faculty')) with check(institution_id=private.current_institution_id());
create policy "institution members manage courses" on public.courses for all to authenticated using(institution_id=private.current_institution_id() and private.current_role() in('super_admin','institution_admin','faculty')) with check(institution_id=private.current_institution_id());
create policy "institution members manage clubs" on public.clubs for all to authenticated using(institution_id=private.current_institution_id() and private.current_role() in('super_admin','institution_admin','club_admin')) with check(institution_id=private.current_institution_id());
create policy "institution members manage club members" on public.club_members for all to authenticated using(institution_id=private.current_institution_id() and private.current_role() in('super_admin','institution_admin','club_admin')) with check(institution_id=private.current_institution_id());
create policy "institution members manage events" on public.events for all to authenticated using(institution_id=private.current_institution_id() and private.current_role() in('super_admin','institution_admin','faculty','club_admin')) with check(institution_id=private.current_institution_id());
create policy "institution members manage registrations" on public.event_registrations for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution members manage attendance sessions" on public.event_attendance_sessions for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution members manage attendance" on public.event_attendance for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution members manage participation" on public.participation_records for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution members manage certificates" on public.certificates for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution members manage notices" on public.notices for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution members manage notifications" on public.notifications for all to authenticated using(institution_id=private.current_institution_id() and (profile_id is null or profile_id=(select auth.uid()) or private.current_role() in('super_admin','institution_admin','faculty'))) with check(institution_id=private.current_institution_id());
create policy "institution members manage circulars" on public.circulars for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution members manage deadlines" on public.deadlines for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution members manage timetable" on public.timetable_entries for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution members manage exams" on public.exams for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution members manage academic sessions" on public.academic_attendance_sessions for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution members manage academic attendance" on public.academic_attendance for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution members manage marks" on public.marks for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution members manage achievements" on public.achievements for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution members manage activity" on public.activity_records for all to authenticated using(institution_id=private.current_institution_id()) with check(institution_id=private.current_institution_id());
create policy "institution admins read audit logs" on public.audit_logs for select to authenticated using(institution_id=private.current_institution_id() and private.current_role() in('super_admin','institution_admin'));
create policy "members insert audit logs" on public.audit_logs for insert to authenticated with check(institution_id=private.current_institution_id());

create or replace function private.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'name',split_part(new.email,'@',1))) on conflict(id) do nothing; return new; end;$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure private.handle_new_user();

create or replace function private.create_participation_from_attendance() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.participation_records(institution_id,event_id,student_id,role) values(new.institution_id,new.event_id,new.student_id,'participant') on conflict(event_id,student_id) do nothing; insert into public.activity_records(institution_id,student_id,activity_type,reference_id,description) values(new.institution_id,new.student_id,'event',new.event_id,'Verified event attendance'); return new; end;$$;
drop trigger if exists attendance_participation_trigger on public.event_attendance;
create trigger attendance_participation_trigger after insert on public.event_attendance for each row execute procedure private.create_participation_from_attendance();