create extension if not exists pgcrypto;
create type public.user_role as enum ('super_admin','institution_admin','faculty','club_admin','student');
create type public.record_status as enum ('active','inactive','archived');
create type public.event_status as enum ('draft','published','registration_closed','live','completed','cancelled');
create type public.registration_status as enum ('registered','waitlisted','cancelled');
create type public.certificate_status as enum ('pending','issued','revoked');

create table if not exists public.institutions(id uuid primary key default gen_random_uuid(),name text not null,code text unique,email text,phone text,website text,status public.record_status not null default 'active',created_at timestamptz not null default now());
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,institution_id uuid references public.institutions(id) on delete set null,display_name text,role public.user_role not null default 'student',status public.record_status not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.departments(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,name text not null,code text not null,created_at timestamptz not null default now(),unique(institution_id,code));
create table if not exists public.students(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,profile_id uuid unique references public.profiles(id) on delete set null,department_id uuid references public.departments(id) on delete set null,student_number text not null,first_name text not null,last_name text not null,email text,phone text,year_of_study smallint,admission_year smallint,status public.record_status not null default 'active',created_at timestamptz not null default now(),unique(institution_id,student_number));
create table if not exists public.courses(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,department_id uuid references public.departments(id) on delete set null,code text not null,name text not null,credits numeric(4,1) default 0,created_at timestamptz not null default now(),unique(institution_id,code));
create table if not exists public.clubs(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,name text not null,slug text not null,description text,status public.record_status not null default 'active',created_at timestamptz not null default now(),unique(institution_id,slug));
create table if not exists public.club_members(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,club_id uuid not null references public.clubs(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,role text not null default 'member',joined_at timestamptz not null default now(),unique(club_id,student_id));
create table if not exists public.events(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,club_id uuid references public.clubs(id) on delete set null,created_by uuid references public.profiles(id) on delete set null,title text not null,description text,start_at timestamptz not null,end_at timestamptz,venue text,capacity integer not null default 0 check(capacity>=0),status public.event_status not null default 'draft',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.event_registrations(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,event_id uuid not null references public.events(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,status public.registration_status not null default 'registered',registered_at timestamptz not null default now(),unique(event_id,student_id));
create table if not exists public.event_attendance(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,event_id uuid not null references public.events(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,checked_in_at timestamptz not null default now(),method text not null default 'qr',unique(event_id,student_id));
create table if not exists public.certificates(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,event_id uuid references public.events(id) on delete set null,student_id uuid not null references public.students(id) on delete cascade,certificate_number text not null,title text not null,status public.certificate_status not null default 'pending',issued_at timestamptz,created_at timestamptz not null default now(),unique(institution_id,certificate_number));
create table if not exists public.notices(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,created_by uuid references public.profiles(id) on delete set null,title text not null,body text not null,published_at timestamptz,expires_at timestamptz,status public.record_status not null default 'active',created_at timestamptz not null default now());
create table if not exists public.academic_attendance_sessions(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,course_id uuid not null references public.courses(id) on delete cascade,faculty_id uuid references public.profiles(id) on delete set null,starts_at timestamptz not null,created_at timestamptz not null default now());
create table if not exists public.academic_attendance(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,session_id uuid not null references public.academic_attendance_sessions(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,present boolean not null default false,marked_at timestamptz not null default now(),unique(session_id,student_id));
create table if not exists public.marks(id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id) on delete cascade,course_id uuid not null references public.courses(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,assessment_name text not null,score numeric(7,2) not null,max_score numeric(7,2) not null,created_at timestamptz not null default now(),unique(course_id,student_id,assessment_name));
create table if not exists public.audit_logs(id uuid primary key default gen_random_uuid(),institution_id uuid references public.institutions(id) on delete cascade,actor_id uuid references public.profiles(id) on delete set null,action text not null,entity_type text not null,entity_id uuid,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

create index if not exists events_institution_start_idx on public.events(institution_id,start_at);
create index if not exists students_institution_idx on public.students(institution_id);
create index if not exists registrations_event_idx on public.event_registrations(event_id);
create index if not exists attendance_event_idx on public.event_attendance(event_id);

create or replace function public.current_institution_id() returns uuid language sql stable security definer set search_path=public as $$select institution_id from public.profiles where id=auth.uid()$$;
create or replace function public.current_role() returns public.user_role language sql stable security definer set search_path=public as $$select role from public.profiles where id=auth.uid()$$;

alter table public.institutions enable row level security;
alter table public.profiles enable row level security;
alter table public.departments enable row level security;
alter table public.students enable row level security;
alter table public.courses enable row level security;
alter table public.clubs enable row level security;
alter table public.club_members enable row level security;
alter table public.events enable row level security;
alter table public.event_registrations enable row level security;
alter table public.event_attendance enable row level security;
alter table public.certificates enable row level security;
alter table public.notices enable row level security;
alter table public.academic_attendance_sessions enable row level security;
alter table public.academic_attendance enable row level security;
alter table public.marks enable row level security;
alter table public.audit_logs enable row level security;
grant usage on schema public to authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;

create policy "members read institution" on public.institutions for select to authenticated using(id=public.current_institution_id());
create policy "users read profiles" on public.profiles for select to authenticated using(id=auth.uid() or institution_id=public.current_institution_id());
create policy "members read departments" on public.departments for select to authenticated using(institution_id=public.current_institution_id());
create policy "staff manage departments" on public.departments for all to authenticated using(institution_id=public.current_institution_id() and public.current_role() in('super_admin','institution_admin')) with check(institution_id=public.current_institution_id());
create policy "members read students" on public.students for select to authenticated using(institution_id=public.current_institution_id());
create policy "staff manage students" on public.students for all to authenticated using(institution_id=public.current_institution_id() and public.current_role() in('super_admin','institution_admin','faculty')) with check(institution_id=public.current_institution_id());
create policy "members read courses" on public.courses for select to authenticated using(institution_id=public.current_institution_id());
create policy "staff manage courses" on public.courses for all to authenticated using(institution_id=public.current_institution_id() and public.current_role() in('super_admin','institution_admin','faculty')) with check(institution_id=public.current_institution_id());
create policy "members read clubs" on public.clubs for select to authenticated using(institution_id=public.current_institution_id());
create policy "staff manage clubs" on public.clubs for all to authenticated using(institution_id=public.current_institution_id() and public.current_role() in('super_admin','institution_admin','club_admin')) with check(institution_id=public.current_institution_id());
create policy "members read club members" on public.club_members for select to authenticated using(institution_id=public.current_institution_id());
create policy "club staff manage members" on public.club_members for all to authenticated using(institution_id=public.current_institution_id() and public.current_role() in('super_admin','institution_admin','club_admin')) with check(institution_id=public.current_institution_id());
create policy "members read events" on public.events for select to authenticated using(institution_id=public.current_institution_id());
create policy "staff create events" on public.events for insert to authenticated with check(institution_id=public.current_institution_id() and created_by=auth.uid() and public.current_role() in('super_admin','institution_admin','faculty','club_admin'));
create policy "staff update events" on public.events for update to authenticated using(institution_id=public.current_institution_id() and public.current_role() in('super_admin','institution_admin','faculty','club_admin')) with check(institution_id=public.current_institution_id());
create policy "members read registrations" on public.event_registrations for select to authenticated using(institution_id=public.current_institution_id());
create policy "students register" on public.event_registrations for insert to authenticated with check(institution_id=public.current_institution_id() and student_id in(select id from public.students where profile_id=auth.uid()));
create policy "staff manage registrations" on public.event_registrations for update to authenticated using(institution_id=public.current_institution_id() and public.current_role() in('super_admin','institution_admin','faculty','club_admin')) with check(institution_id=public.current_institution_id());
create policy "members read event attendance" on public.event_attendance for select to authenticated using(institution_id=public.current_institution_id());
create policy "staff record attendance" on public.event_attendance for insert to authenticated with check(institution_id=public.current_institution_id() and public.current_role() in('super_admin','institution_admin','faculty','club_admin'));
create policy "members read certificates" on public.certificates for select to authenticated using(institution_id=public.current_institution_id());
create policy "staff manage certificates" on public.certificates for all to authenticated using(institution_id=public.current_institution_id() and public.current_role() in('super_admin','institution_admin','faculty','club_admin')) with check(institution_id=public.current_institution_id());
create policy "members read notices" on public.notices for select to authenticated using(institution_id=public.current_institution_id());
create policy "staff manage notices" on public.notices for all to authenticated using(institution_id=public.current_institution_id() and public.current_role() in('super_admin','institution_admin','faculty')) with check(institution_id=public.current_institution_id());
create policy "members read academic sessions" on public.academic_attendance_sessions for select to authenticated using(institution_id=public.current_institution_id());
create policy "faculty create academic sessions" on public.academic_attendance_sessions for insert to authenticated with check(institution_id=public.current_institution_id() and public.current_role() in('super_admin','institution_admin','faculty'));
create policy "members read academic attendance" on public.academic_attendance for select to authenticated using(institution_id=public.current_institution_id());
create policy "faculty manage academic attendance" on public.academic_attendance for all to authenticated using(institution_id=public.current_institution_id() and public.current_role() in('super_admin','institution_admin','faculty')) with check(institution_id=public.current_institution_id());
create policy "marks read" on public.marks for select to authenticated using(institution_id=public.current_institution_id() and(public.current_role() in('super_admin','institution_admin','faculty') or student_id in(select id from public.students where profile_id=auth.uid())));
create policy "staff manage marks" on public.marks for all to authenticated using(institution_id=public.current_institution_id() and public.current_role() in('super_admin','institution_admin','faculty')) with check(institution_id=public.current_institution_id());
create policy "staff read audit logs" on public.audit_logs for select to authenticated using(institution_id=public.current_institution_id() and public.current_role() in('super_admin','institution_admin'));
create policy "members insert audit logs" on public.audit_logs for insert to authenticated with check(institution_id=public.current_institution_id());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'name',split_part(new.email,'@',1))) on conflict(id) do nothing; return new; end;$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();