export type Field={name:string;label:string;type:"text"|"number"|"datetime-local"|"date"|"select"|"textarea";options?:string[];required?:boolean};
export type ModuleConfig={resource:string;title:string;eyebrow:string;description:string;fields:Field[];columns:string[];workflow?:string[]};
export const MODULES:Record<string,ModuleConfig>={
students:{resource:"students",title:"Students",eyebrow:"Campus / Students",description:"Institution-wide student directory and identity record.",fields:[{name:"student_number",label:"Student ID",type:"text",required:true},{name:"first_name",label:"First name",type:"text",required:true},{name:"last_name",label:"Last name",type:"text",required:true},{name:"email",label:"Email",type:"text"},{name:"year_of_study",label:"Year",type:"number"}],columns:["student_number","first_name","last_name","email","year_of_study","status"]},
clubs:{resource:"clubs",title:"Clubs",eyebrow:"Student Life / Clubs",description:"Create clubs, manage ownership and connect them to events.",fields:[{name:"name",label:"Club name",type:"text",required:true},{name:"slug",label:"Slug",type:"text",required:true},{name:"description",label:"Description",type:"textarea"}],columns:["name","slug","description","status"]},
events:{resource:"events",title:"Events",eyebrow:"Campus / Events",description:"The source record for registration, attendance, participation and certificates.",fields:[{name:"title",label:"Event name",type:"text",required:true},{name:"description",label:"Description",type:"textarea"},{name:"start_at",label:"Start",type:"datetime-local",required:true},{name:"end_at",label:"End",type:"datetime-local"},{name:"venue",label:"Venue",type:"text"},{name:"capacity",label:"Capacity",type:"number",required:true}],columns:["title","start_at","venue","capacity","status"],workflow:["Draft","Published","Registration","Attendance","Participation","Certificate","Report"]},
registrations:{resource:"event_registrations",title:"Registrations",eyebrow:"Student Life / Registrations",description:"Event registrations tied to real student and event records.",fields:[{name:"event_id",label:"Event ID",type:"text",required:true},{name:"student_id",label:"Student ID",type:"text",required:true}],columns:["event_id","student_id","status","registered_at"]},
attendance:{resource:"event_attendance",title:"Event Attendance",eyebrow:"Student Life / Attendance",description:"Verified event check-ins and the audit trail behind participation.",fields:[{name:"event_id",label:"Event ID",type:"text",required:true},{name:"student_id",label:"Student ID",type:"text",required:true}],columns:["event_id","student_id","checked_in_at","method"]},
certificates:{resource:"certificates",title:"Certificates",eyebrow:"Student Life / Certificates",description:"Issue and verify certificates against participation records.",fields:[{name:"event_id",label:"Event ID",type:"text"},{name:"student_id",label:"Student ID",type:"text",required:true},{name:"certificate_number",label:"Certificate number",type:"text",required:true},{name:"title",label:"Certificate title",type:"text",required:true}],columns:["certificate_number","title","student_id","status","issued_at"]},
courses:{resource:"courses",title:"Courses",eyebrow:"Academics / Courses",description:"Academic course catalogue used by attendance, marks and examinations.",fields:[{name:"code",label:"Course code",type:"text",required:true},{name:"name",label:"Course name",type:"text",required:true},{name:"credits",label:"Credits",type:"number"}],columns:["code","name","credits"]},
academic_attendance:{resource:"academic_attendance_sessions",title:"Class Attendance",eyebrow:"Academics / Attendance",description:"Create class sessions and record student attendance.",fields:[{name:"course_id",label:"Course ID",type:"text",required:true},{name:"starts_at",label:"Session time",type:"datetime-local",required:true}],columns:["course_id","starts_at","faculty_id"]},
marks:{resource:"marks",title:"Marks",eyebrow:"Academics / Marks",description:"Assessment scores linked to courses and students.",fields:[{name:"course_id",label:"Course ID",type:"text",required:true},{name:"student_id",label:"Student ID",type:"text",required:true},{name:"assessment_name",label:"Assessment",type:"text",required:true},{name:"score",label:"Score",type:"number",required:true},{name:"max_score",label:"Maximum",type:"number",required:true}],columns:["course_id","student_id","assessment_name","score","max_score"]},
timetable:{resource:"timetable_entries",title:"Timetable",eyebrow:"Academics / Timetable",description:"Weekly teaching schedule for courses, rooms and faculty.",fields:[{name:"course_id",label:"Course ID",type:"text",required:true},{name:"day_of_week",label:"Day",type:"select",options:["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],required:true},{name:"start_time",label:"Start",type:"text",required:true},{name:"end_time",label:"End",type:"text",required:true},{name:"room",label:"Room",type:"text"}],columns:["course_id","day_of_week","start_time","end_time","room"]},
exams:{resource:"exams",title:"Exams",eyebrow:"Academics / Exams",description:"Exam schedules linked to courses and academic periods.",fields:[{name:"course_id",label:"Course ID",type:"text",required:true},{name:"name",label:"Exam",type:"text",required:true},{name:"starts_at",label:"Date & time",type:"datetime-local",required:true},{name:"room",label:"Room",type:"text"}],columns:["name","course_id","starts_at","room"]},
notices:{resource:"notices",title:"Notices",eyebrow:"Communication / Notices",description:"Publish institution-wide notices with controlled visibility.",fields:[{name:"title",label:"Title",type:"text",required:true},{name:"body",label:"Notice",type:"textarea",required:true},{name:"published_at",label:"Publish",type:"datetime-local"}],columns:["title","published_at","status"]},
notifications:{resource:"notifications",title:"Notifications",eyebrow:"Communication / Notifications",description:"Targeted notifications generated by institutional workflows.",fields:[{name:"title",label:"Title",type:"text",required:true},{name:"body",label:"Message",type:"textarea",required:true}],columns:["title","body","created_at","read_at"]},
circulars:{resource:"circulars",title:"Circulars",eyebrow:"Communication / Circulars",description:"Formal circular archive with searchable institutional records.",fields:[{name:"title",label:"Circular title",type:"text",required:true},{name:"body",label:"Circular",type:"textarea",required:true},{name:"published_at",label:"Publish",type:"datetime-local"}],columns:["title","published_at","created_at"]},
deadlines:{resource:"deadlines",title:"Deadlines",eyebrow:"Communication / Deadlines",description:"Important academic and administrative deadlines.",fields:[{name:"title",label:"Deadline",type:"text",required:true},{name:"due_at",label:"Due",type:"datetime-local",required:true},{name:"description",label:"Description",type:"textarea"}],columns:["title","due_at","status"]},
participation:{resource:"participation_records",title:"Participation",eyebrow:"Student Life / Participation",description:"Automatically generated participation records from verified event attendance.",fields:[{name:"event_id",label:"Event ID",type:"text",required:true},{name:"student_id",label:"Student ID",type:"text",required:true},{name:"role",label:"Participation role",type:"text"}],columns:["event_id","student_id","role","created_at"]},
achievements:{resource:"achievements",title:"Achievements",eyebrow:"Student Profile / Achievements",description:"Student achievements across academics and campus life.",fields:[{name:"student_id",label:"Student ID",type:"text",required:true},{name:"title",label:"Achievement",type:"text",required:true},{name:"category",label:"Category",type:"text"},{name:"achieved_on",label:"Date",type:"date"}],columns:["student_id","title","category","achieved_on"]},
activity:{resource:"activity_records",title:"Activity Record",eyebrow:"Student Profile / Activity",description:"Unified student participation history across campus activities.",fields:[{name:"student_id",label:"Student ID",type:"text",required:true},{name:"activity_type",label:"Activity",type:"text",required:true},{name:"reference_id",label:"Reference ID",type:"text"},{name:"description",label:"Description",type:"textarea"}],columns:["student_id","activity_type","reference_id","created_at"]},
academic_record:{resource:"academic_record",title:"Academic Record",eyebrow:"Student Profile / Academic",description:"Read-only academic record assembled from courses, marks and attendance.",fields:[],columns:[]},
reports:{resource:"reports",title:"Reports",eyebrow:"Administration / Reports",description:"Operational reporting over the institution's live records.",fields:[],columns:[]}
};